### ISSUE TITLE
Enforce consistent code formatting in development

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/waveorder#332]
**Problem**

Although we depend on the `black` formatter in the `[dev]` requirements, it is not currently consistently used, and there are unconventional formatting (wrt PEP 8) widespread in the code base.

**Proposed solution**

- [x] We should arrange a PR that formats the existing code. (Done: mehta-lab/recOrder#229)
- [x] The contributors should be required to format their code with the `black` formatter we specify in the `[dev]` requirement before pushing to the repository. (#185)
- [ ] (Optionally) we can also [incorporate formatting formatting in our GItHub Actions workflow](https://black.readthedocs.io/en/stable/integrations/github_actions.html)..

**Example**

`black` can be executed from the command line if the user has the `[dev]` environment activated.
If you are using a modern IDE, formatting can also be done by selecting the `black` installed in their virtual environment as the formatter backend (VS Code: `^/⌘ ⇧  P` and type 'format document with...').
